name: Checkstyle

on: [ pull_request ]

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Run Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest
      - name: Upload Checkstyle results
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-results
          path: build/reports/checkstyle/